FROM ubuntu:16.04

# install basic stuff

RUN apt-get update -y && apt-get install -y --no-install-recommends \
    build-essential       \
    cmake                 \
    python-pip            \
    python-setuptools     \
    git                   \
    vim

RUN pip install --upgrade pip

# install optional dependencies

RUN apt-get install -y    \
    libpthread-stubs0-dev \
    libtbb-dev

# install linters

RUN apt-get install -y    \
    clang-format-4.0

RUN pip install cpplint

# configure and build NNPACK

# Install the latest Ninja.
# RUN apt-get install ninja-build
RUN git clone https://github.com/ninja-build/ninja /tmp/ninja \
 && cd /tmp/ninja \
 && git checkout v1.8.2 \
 && ./configure.py --bootstrap \
 && mv ninja /usr/bin/ninja \
 && rm -rf /tmp/ninja

RUN pip install --upgrade setuptools && \
    pip install wheel && \
    pip install ninja-syntax

RUN pip install --upgrade git+https://github.com/tiny-dnn/PeachPy
RUN pip install --upgrade git+https://github.com/tiny-dnn/confu

WORKDIR /opt
RUN git clone https://github.com/tiny-dnn/NNPACK.git && \
    cd NNPACK && \
    confu setup && \
    python ./configure.py && \
    ninja

# install opencl and viennacl

RUN apt-get install -y \
    ocl-icd-opencl-dev \ 
    libviennacl-dev

# build and configure libdnn

WORKDIR /opt
RUN git clone https://github.com/masa-matsu/libdnn.git && \
    cd libdnn && mkdir build && cd build && \
    cmake .. && make -j2

WORKDIR /opt
RUN git clone https://github.com/masa-matsu/tiny-dnn.git